### ISSUE TITLE
Add Nasp to Service Mesh Landscape

### ISSUE THREAD

**Issue by vishalvivekm** [cisco-open/libnasp#184]
We, at [Layer5](https://layer5.io), are curating our [Service Mesh Landscape](https://layer5.io/service-mesh-landscape) to include Nasp.
There is a collection of functional capabilities and non-functionality capabilities that we track in the tables and I am requesting any of the project representatives to assist in accurately representing Nasp within the landscape.

Here is the link to the corresponding issue: https://github.com/layer5io/layer5/issues/4350.
Thanks!

**Comment by vishalvivekm** [comment]
@bonifaido @baluchicken @waynz0r can you please help with the ongoing curation?

**Comment by waynz0r** [comment]
> @bonifaido @baluchicken @waynz0r can you please help with the ongoing curation?

Sure, we are happy to help.

**Comment by vishalvivekm** [comment]
> > @bonifaido @baluchicken @waynz0r can you please help with the ongoing curation?
> 
> Sure, we are happy to help.

Hi @waynz0r,
Please take a look at: https://layer5.io/service-mesh-landscape.
To add Nasp, Details are needed to update the timeline and fill in the matrix:
https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape
As a representative of the project, it would be helpful if you make this update (being the most knowledgeable of it) or you can share the details in the issue's comments on layer5 repo https://github.com/layer5io/layer5/issues/4350.
Thanks!
